name: AdvancedPet
main: fr.nocsy.almpet.AdvancedPet
version: 0.3.0
description: Plugin made by Nocsy
depends:
  - WorldGuard
  - MythicMobs
  - ModelEngine
author: Nocsy
api-version: 1.16
commands:
  advancedpet:
    description: Command to manage your pets
    Usage: /advancedpet